### ISSUE TITLE
Separate plugins into individual repos?

### ISSUE THREAD

**Issue by jdonaldson10** [SamWM/jQuery-Plugins#101]
Would it be an idea to separate this out into a repo per project?

By doing this it would be much more modular. It would also make is easy to set-up bower/npm to allow people to easily pull the individual plugins into their projects.

**Comment by SamWM** [comment]
Have started the process, so far:

https://github.com/SamWM/jquery-numeric
https://github.com/SamWM/jquery-checkboxes

**Comment by jdonaldson10** [comment]
@SamWM good stuff! Much appreciated :smile:
