### ISSUE TITLE
Crashes on IE11 when entering any value on a numeric textbox

### ISSUE THREAD

**Issue by manojkumarg** [SamWM/jQuery-Plugins#62]
Hi,

On IE 11 this plugin crashes when entering any value on a numeric textbox because document.selection.createRange() is not supported from IE 11 

http://msdn.microsoft.com/en-us/library/ie/ms535869%28v=vs.85%29.aspx
## Error Detail

Unable to get property 'createRange' of undefined or null reference 
line 255 on jquery.numeric.js 

Please can you look into this and fix this issue.

**Comment by smokey1383** [comment]
Thank you djackie...I know this was from a couple of years ago, but your fix just saved me today!!!

**Comment by abdessamadjadid** [comment]
To resolve this issue you can replace your code with this code under . it work for internet explorer version from IE 5 To IE 11 and the Jquery.numeric.js plugin file  version must to be 1.4.1

  // Based on code from http://javascript.nwbox.com/cursor_position/ (Diego Perini <dperini@nwbox.com>)
    $.fn.getSelectionStart = function (o) {
        if (o.createTextRange) {
            var r;
            if (typeof document.selection == "undefined") {
                //On IE < 9 && IE >= 11 : "document.selection" is deprecated and you should use "document.getSelection()"
                //https://github.com/SamWM/jQuery-Plugins/issues/62
                r = document.getSelection();
            } else {
                r = document.selection.createRange().duplicate();
                r.moveEnd('character', o.value.length);
            }
            if (r.text === '' || r.text === undefined) return o.value.length;
            return o.value.lastIndexOf(r.text);
        } else { return o.selectionStart; }
    } 


[jquery.numeric.txt](https://github.com/SamWM/jQuery-Plugins/files/2988628/jquery.numeric.txt)
