### ISSUE TITLE
It would be nice to get these plugins up on bower.

### ISSUE THREAD

**Issue by Duder-onomy** [SamWM/jQuery-Plugins#80]
I have SamWM's jquery.numeric REPO up on bower:
http://bower.io/search/?q=jquery_numeric_samw

It would be nice if this was supported and maintained by the author(s) because there are a ton of other copies of jquery.numeric on bower, and they are all the old version.  Only have one jquery.numeric up on bower, and it is the authors version. 

If someone was to try and use this library with version control, they would have to do some sluething to find the right one.

**Comment by drydevelopment** [comment]
:+1: I could see each jQuery plugin in this repository being their own repositories, too.

**Comment by SamWM** [comment]
Migrating to new repositories
https://github.com/SamWM/jquery-numeric
https://github.com/SamWM/jquery-checkboxes

**Comment by slevesque** [comment]
What about jquery-selectboxes in bower ?
